travis:
  secure:
    BINSTAR_TOKEN: jVn1aM6dgFKziz9W1Sj1qITfJfj0LuGs8nCv8rzlWSa2VgKa8kkAbdt985WCbQmTMjwmJjrkP28OrHQPtZHn8289pZTeNMHr2KZU6Xli85lCkiwAW2oYgUHGpFB1xu5UD7ymVw5Ua0nfTTB7FubVMApqFGvEjgwHP66UMrvlBTeQqOmuFWblLDjv+iV+pAySPFEg6PCLTkTL93DD3ucdtpyKAQKY00YHQjkuZ6EKuBeQIPc7BQOwyihpuPeom8H+J31XG7f9MA190iAK9/m+O7GOZ+bXs4hjZcPrWa9zMI/MH46XhImn+lR1avAhtoqKBib4LHOohNYJ+XxWSrszMwpzH/mCGOwcfz+dgX0TVPYcmgsoOprvQ7+dXTELZIAQLG4Vs0fohrw3OaMgpIw3cfpp5hmw1J7dDqzaOv30wIS8JcnRxyxAHtRtddh8KPn2KKDN5SPG+RdhhqmYakltH6Z3qf2Sg+yIM7si8tW0R/da6tc0mxI9AW2mHlSnZNWmb2vPRDz5E7DYVYj4aw6RmrJIl1X5NUKU11kKR/+pEoeg7cIqdwZH6cuwJDS1ahCrxs4zg4/Z/G0MD7RzMRxUh8adjuldia+n0U5e0qIQ+vOwcRCp816//GX+4hGVJc8jnYJ0z8YVBjCjF9xOf4meb5CK6v1SntdukuSdRgfL3UQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
